# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                             #
#                          Whack Me                           #
#                          Despical                           #
#                                                             #
#              https://www.patreon.com/despical               #
#            https://www.buymeacoffee.com/despical            #
#                                                             #
#            Donations are really appreciated!  <3            #
#                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# In-game blocks.
Point-Blocks:
  # Enable this option if you want textured skull item instead.
  # Then you can be able to replace item names with skull URLs.
  Skulls-Enabled: false
  Punch-Me: GREEN_TERRACOTTA
  Dont-Punch-Me: RED_TERRACOTTA
  Ouch: CYAN_TERRACOTTA

# Should we create a game bar for in-game player?
# See messages.yml for game bar messages.
Boss-Bar-Enabled: true

# Should we enable our MySQL support?
# See mysql.yml for detailed information.
Database-Enabled: false

# Enable inventory manager for your games? (Very useful feature for MULTI ARENA)
# This saves inventory of players and restores it after player leaves arena.
# Saved elements: max health, health, food, experience, full inventory, armor contents, and more.
Inventory-Manager-Enabled: true

# Should we clear player's inventory on join and after leaving the game area?
# Also disable inventory manager option above before enabling this option.
Clear-Inventory: true

# Should we clear player's active potion effects when player join the arena?
Clear-Effects: true

# Should we block the in-game leave command?
Block-Leave-Command: false

# Should we register our rewards factory? This factory provides custom rewards
# on a specific conditionals such as game end or when player clicks point blocks.
# See rewards.yml file for more detailed information.
Rewards-Enabled: false

# Should we format the chat messages?
# See messages.yml to change format.
Chat-Format-Enabled: true

# Point blocks are maximum raised by total of 0.65 in Y axis.
Point-Block-Y-Multiplier: 0.05

# The gameplay time for each arena. Default is 30 seconds.
Gameplay-Time: 30

# This value can not be less than 1 and can not be higher than 8.
# Minimum value of the point blocks that will be spawned around the player.
Minimum-Points: 4

# This value can not be less than 1 and can not be higher than 8.
# Maximum value of the point blocks that will be spawned around the player.
Maximum-Points: 8

# The sound plays when player clicks the correct point block.
Point-Sound: "ORB_PICKUP"

# The sound plays when player clicks the incorrect point block.
Minus-Point-Sound: "NOTE_BASS"

# The delay between hitting players.
Hit-Cooldown-Delay: 16

# Commands which can be used in game, remove all of them to disable.
Whitelisted-Commands:
  - me
  - help

# Should we block every not Whack Me associated commands in game?
Block-Commands: true

# Should we send any random tip when the setup menu opens?
Send-Setup-Tips: true

# Should we check for updates on plugin start and after any admin join?
Update-Notifier-Enabled: true

# The permission that player needs to join to game.
# Leave the section empty if you don't want to set.
Join-Permission: ""

# No way! You've reached the end! But... where's the dragon!?