# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                             #
#                          Whack Me                           #
#                          Despical                           #
#                                                             #
#                https://discord.gg/uXVU8jmtpU                #
#            https://www.buymeacoffee.com/despical            #
#                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Point block settings.
Point-Blocks:
  # Entity removal is still going to be executed in main thread.
  # This option may decrease the amount of lag if there are multiple
  # instances running at the same time.
  Run-Async: false
  # Period of point handler thread. If you decrease that value the blocks
  # will move faster and if you increase the period then they'll move slower.
  # This option should be edited considering Y multiplier.
  # Best way to make blocks move faster is increasing multiplier below.
  Ticks: 8
  # Point blocks are maximum raised by total of 0.65 in Y axis.
  Y-Multiplier: 0.05
  # How many milliseconds should any point block wait in the air?
  Wait-Ms: 12
  # Point blocks can be rotated around the vertical axis.
  Rotations:
    # Values below are represented to yaw of point blocks in the game.
    Punch-Me: "0:0:0:0:0:0:0:0"
    Dont-Punch-Me: "0:0:0:0:0:0:0:0"
    Ouch: "0:0:0:0:0:0:0:0"
  # The default point block materials.
  Default:
    # For custom skulls: "skull:VALUE"
    Punch-Me: GREEN_TERRACOTTA
    Dont-Punch-Me: RED_TERRACOTTA
    Ouch: CYAN_TERRACOTTA
  Custom:
    # The ID of the arena.
    default:
      # For custom skulls: "skull:VALUE"
      Punch-Me: GREEN_TERRACOTTA
      Dont-Punch-Me: RED_TERRACOTTA
      Ouch: CYAN_TERRACOTTA

# Should we create a game bar for in-game player?
# See messages.yml for game bar messages.
Boss-Bar-Enabled: true

# Should we enable our MySQL support?
# See mysql.yml for detailed information.
Database-Enabled: false

# Enable Inventory Manager for your games? (VERY USEFUL feature for MULTI ARENA)
# This saves inventory of players and restores it after player leaves arena.
# Saved elements: max health, health, food, experience, full inventory, armor contents, and more.
Inventory-Manager:
  Enabled: true
  # Usable attributes:
  #  game-mode, hunger, exp, level
  #  health, max-health, health-scale
  #  saturation, allow-flight, fire-ticks
  Do-Not-Restore:
    - "max-health"
    - "health-scale"

# Should we clear player's inventory on join and after leaving the game area?
# Also disable inventory manager option above before enabling this option.
Clear-Inventory: true

# Should we clear player's active potion effects when player join the arena?
Clear-Effects: true

# Should we block the in-game leave command?
Block-Leave-Command: false

# Should we format the chat messages?
# See messages.yml to change format.
Chat-Format-Enabled: true

# The gameplay time for each arena. Default is 30 seconds.
Gameplay-Time: 30

# The statistics saving rate, in seconds. (0 = save the stats on server shutdown/reload)
Statistic-Saving-Period: 300

# Set NONE to disable.
Sounds:
  # The sound plays when player clicks the correct point block.
  Point: "ORB_PICKUP"

  # The sound plays when player clicks the incorrect point block.
  Minus-Point: "NOTE_BASS"

# 20 = no hit cooldown, 4 is the default value.
# The smaller value the slower hits.
Hit-Cooldown-Delay: 20

# Should players wait a certain amount of time before playing again Whack Me? (in seconds)
Game-Cooldown: 0

# Commands which can be used in game, remove all of them to disable.
Whitelisted-Commands:
  - me
  - help

# Should we block every not Whack Me associated commands in game?
Block-Commands: true

# Should we check for updates on plugin start and after any admin join?
Update-Notifier-Enabled: true

# The permission that player needs to join to game.
# Leave the section empty if you don't want to set.
Join-Permission: ""

# No way! You've reached the end! But... where's the dragon!?