name: WhackMe
main: me.despical.whackme.WhackMe
author: Despical
version: ${project.version}
website: https://www.spigotmc.org/resources/104912

api-version: 1.13
softdepend:
  - Multiverse-Core
  - PlaceholderAPI
  - MultiWorld

permissions:
  wm.admin.*:
    default: op
    children:
      wm.admin: true
      wm.admin.create: true
      wm.admin.delete: true
      wm.admin.edit: true
      wm.admin.list: true
      wm.admin.help: true
      wm.admin.reload: true
      wm.admin.kick: true
      wm.admin.sign.create: true
      wm.admin.sign.break: true